[package]
name = "ryor"
version = "0.1.0"
edition = "2024"

[build]
target = "target.json"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.11.10"
lazy_static = "1.5.0"
volatile = { version = "0.6.1", features = ["spin_no_std"] }
